<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_register</name>
   <tag></tag>
   <elementGuidId>2d5987c5-a684-4990-8366-b448df57c3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a115c00-1561-4f18-92c1-716b4641411d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bangalorejobseekers.com/register/?redirect_to=https%3A%2F%2Fwww.bangalorejobseekers.com%2Fcreate-listing%2F</value>
      <webElementGuid>ab1ca417-b189-4925-b6ed-75740e3c4ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>67abd4fe-4cbc-4431-a94a-fb535278b137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;content-wrap content-wrap-clear&quot;]/div[@class=&quot;notice process-error&quot;]/div[1]/a[2]</value>
      <webElementGuid>b2e48beb-5605-40eb-bcc2-f53bdc7936c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/a[2]</value>
      <webElementGuid>1f92bc65-31ac-4a26-9b1e-ad3bd9ab4eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'register')]</value>
      <webElementGuid>98db8e53-43df-4b94-bba0-5e759561f3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='login'])[1]/following::a[1]</value>
      <webElementGuid>e0733376-971c-45a1-8ca3-7d0b17fc1438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ’s'])[1]/preceding::a[1]</value>
      <webElementGuid>2c6abcc6-2eee-4381-8079-b702f7cdde69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::a[2]</value>
      <webElementGuid>4c69b38c-4886-4213-aa74-028e965297a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='register']/parent::*</value>
      <webElementGuid>5a589386-41b9-44c6-a99b-52551be8c8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bangalorejobseekers.com/register/?redirect_to=https%3A%2F%2Fwww.bangalorejobseekers.com%2Fcreate-listing%2F')]</value>
      <webElementGuid>c9247497-12f4-43fd-99a2-b84424bfc2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>3bdb02c2-d197-45c3-8367-06959da35917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bangalorejobseekers.com/register/?redirect_to=https%3A%2F%2Fwww.bangalorejobseekers.com%2Fcreate-listing%2F' and (text() = 'register' or . = 'register')]</value>
      <webElementGuid>293b9e63-c8bb-4ba2-b0e3-3595cf687c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
